# Generated by Django 3.0.6 on 2020-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(blank=True, choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5),
        ),
    ]
